### ISSUE TITLE
URL with trailing slash causes troubles

### ISSUE THREAD

**Issue by chevdor** [r7wx/easy-gate#4] opened 2022-05-03 20:47 UTC
Using a URL with a trailing slash such as `http://foo/` seems to be improperly handled and results in the url `http//foo` (the missing `:` is not a typo).

**Comment by r7wx** [comment] 2022-05-03 20:57
I am not able to reproduce this issue. What could be happening is that you have an error in your configuration file thus the configuration is still the same and not updating (try to add a new test service and see if you can see it on the webapp). I will improve error handling in future.

**Comment by chevdor** [comment] 2022-05-04 07:31
I cannot reproduce the issue right now but I got it 3 times in a raw adding 3 new services.
- edit file
- copy url (with trailing slash)
- paste
- save
- reload
- open link => http//...

Removing the trailign slashes fixes the issue. Putting it back in does not seem to retrigger the issue.

**Comment by r7wx** [comment] 2022-05-04 11:15
Closing this issue for now, since there are not enough information to reproduce the bug.
Next release will be published soon, so feel free to open it again if you will face the same problem again.

**Closed by r7wx** 2022-05-04 11:15 UTC
